; This file was auto-generated by drush_make
core = 6.x

api = 2

; Latest Pressflow from Omega8cc
projects[pressflow][type] = "core"
projects[pressflow][download][type] = "git"
projects[pressflow][download][url] = "git://github.com/omega8cc/pressflow6.git"
projects[pressflow][download][branch] = "master"


; Modules set for specific version or patched
; -- revisit these occasionally and try to upgrade or improve
projects[] = "context"
projects[context][version] = "2.1"

; TODO patch!
projects[] = "gmap"
projects[gmap][version] = "1.x-dev"

projects[] = "notifications"
projects[notifications][version] = "4.x-dev"

projects[] = "recaptcha"
projects[recaptcha][version] = "1.x-dev"

  
; Modules
projects[] = "abuse"
projects[] = "views_bulk_operations"
projects[] = "admin_menu"
projects[] = "advanced_forum"
projects[] = "author_pane"
projects[] = "auto_nodetitle"
projects[] = "autoload"
projects[] = "backup_migrate"
projects[] = "service_links"
projects[] = "better_formats"
projects[] = "block_class"
projects[] = "ctools"
projects[] = "calendar"
projects[] = "cck_private_fields"
projects[] = "coder"
projects[] = "coder_tough_love"
projects[] = "colorbox"
projects[] = "contact"
projects[] = "cck"
projects[] = "content_access"
projects[] = "content_profile"
projects[] = "content_taxonomy"
projects[] = "cnr"
projects[] = "custom_breadcrumbs"
projects[] = "customerror"
projects[] = "date"
projects[] = "devel"
projects[] = "email"
projects[] = "emfield"
projects[] = "features"
projects[] = "feeds"
projects[] = "filefield"
projects[] = "fivestar"
projects[] = "google_analytics"
projects[] = "hierarchical_select"
projects[] = "image_resize_filter"
projects[] = "imageapi"
projects[] = "imagecache"
projects[] = "imagefield"
projects[] = "imce"
projects[] = "imce_wysiwyg"
projects[] = "insert"
projects[] = "itweak_upload"
projects[] = "job_scheduler"
projects[] = "jquery_ui"
projects[] = "jquery_update"
projects[] = "link"
projects[] = "location"
projects[] = "logintoboggan"
projects[] = "mail_logger"
projects[] = "maxlength"
projects[] = "media_vimeo"
projects[] = "media_youtube"
projects[] = "menu_block"
projects[] = "mimemail"
projects[] = "multicolumncheckboxesradios"
projects[] = "node_limitnumber"
projects[] = "nodeaccess_userreference"
projects[] = "nodeauthor"
projects[] = "nodehierarchy"
projects[] = "nodequeue"
projects[] = "og"
projects[] = "panels"
projects[] = "path_redirect"
projects[] = "pathauto"
projects[] = "pathologic"
projects[] = "publishcontent"
projects[] = "quicktabs"
projects[] = "revision_deletion"
projects[] = "rules"
projects[] = "site_map"
projects[] = "stringoverrides"
projects[] = "strongarm"
projects[] = "tagadelic"
projects[] = "tagadelic_views"
projects[] = "terms_of_use"
projects[] = "token"
projects[] = "unique_field"
projects[] = "views"
projects[] = "views_bonus"
projects[] = "views_customfield"
projects[] = "views_datasource"
projects[] = "views_slideshow"
projects[] = "votingapi"
projects[] = "web_widgets"
projects[] = "webform"
projects[] = "wysiwyg"
projects[] = "xmlsitemap"


; Custom modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_pse_widget][download][type] = ""
projects[transition_pse_widget][download][url] = ""
projects[transition_pse_widget][type] = "module"
projects[transition_pse_widget][subdir] = "sites/all/modules/custom/features/transition_pse_widget"



; Features
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[initiatives_directory][download][type] = ""
projects[initiatives_directory][download][url] = ""
projects[initiatives_directory][type] = "module"
projects[initiatives_directory][subdir] = "sites/all/modules/custom/features/initiatives_directory"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_alert_web_contacts][download][type] = ""
projects[transition_alert_web_contacts][download][url] = ""
projects[transition_alert_web_contacts][type] = "module"
projects[transition_alert_web_contacts][subdir] = "sites/all/modules/custom/features/transition_alert_web_contacts"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_events][download][type] = ""
projects[transition_events][download][url] = ""
projects[transition_events][type] = "module"
projects[transition_events][subdir] = "sites/all/modules/custom/features/transition_events"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_import_blogs][download][type] = ""
projects[transition_import_blogs][download][url] = ""
projects[transition_import_blogs][type] = "module"
projects[transition_import_blogs][subdir] = "sites/all/modules/custom/features/transition_import_blogs"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_network_projects][download][type] = ""
projects[transition_network_projects][download][url] = ""
projects[transition_network_projects][type] = "module"
projects[transition_network_projects][subdir] = "sites/all/modules/custom/features/transition_network_projects"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_news][download][type] = ""
projects[transition_news][download][url] = ""
projects[transition_news][type] = "module"
projects[transition_news][subdir] = "sites/all/modules/custom/features/transition_news"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_people][download][type] = ""
projects[transition_people][download][url] = ""
projects[transition_people][type] = "module"
projects[transition_people][subdir] = "sites/all/modules/custom/features/transition_people"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_raise_alerts_for_profiles][download][type] = ""
projects[transition_raise_alerts_for_profiles][download][url] = ""
projects[transition_raise_alerts_for_profiles][type] = "module"
projects[transition_raise_alerts_for_profiles][subdir] = "sites/all/modules/custom/features/transition_raise_alerts_for_profiles"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_themes][download][type] = ""
projects[transition_themes][download][url] = ""
projects[transition_themes][type] = "module"
projects[transition_themes][subdir] = "sites/all/modules/custom/features/transition_themes"


; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[TTtriggers][download][type] = ""
projects[TTtriggers][download][url] = ""
projects[TTtriggers][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cookie_cache_bypass][download][type] = ""
projects[cookie_cache_bypass][download][url] = ""
projects[cookie_cache_bypass][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ijk_plugins][download][type] = ""
projects[ijk_plugins][download][url] = ""
projects[ijk_plugins][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[path_alias_cache][download][type] = ""
projects[path_alias_cache][download][url] = ""
projects[path_alias_cache][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_extras][download][type] = ""
projects[transition_extras][download][url] = ""
projects[transition_extras][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_project_massage][download][type] = ""
projects[transition_project_massage][download][url] = ""
projects[transition_project_massage][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_pse][download][type] = ""
projects[transition_pse][download][url] = ""
projects[transition_pse][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_sharing_engine_client][download][type] = ""
projects[transition_sharing_engine_client][download][url] = ""
projects[transition_sharing_engine_client][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_site_network][download][type] = ""
projects[transition_site_network][download][url] = ""
projects[transition_site_network][type] = "module"



; Themes
projects[] = "rootcandy"
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition][download][type] = ""
projects[transition][download][url] = ""
projects[transition][type] = "theme"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition2][download][type] = ""
projects[transition2][download][url] = ""
projects[transition2][type] = "theme"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transitioncms][download][type] = ""
projects[transitioncms][download][url] = ""
projects[transitioncms][type] = "theme"
