; This file was auto-generated by drush_make
core = 6.x

api = 2

; Latest Pressflow from Omega8cc
projects[pressflow][type] = "core"
projects[pressflow][download][type] = "git"
projects[pressflow][download][url] = "git://github.com/omega8cc/pressflow6.git"
projects[pressflow][download][branch] = "master"


; Modules set for specific version or patched
; -- revisit these occasionally and try to upgrade or use standard versions
projects[] = "context"
projects[context][version] = "2.1"

; TODO patch!
projects[] = "gmap"
projects[gmap][version] = "1.x-dev"

projects[] = "notifications"
projects[notifications][version] = "4.x-dev"

projects[] = "recaptcha"
projects[recaptcha][version] = "1.x-dev"

  
; Modules
projects[abuse][subdir] = "contrib"
projects[views_bulk_operations][subdir] = "contrib"
projects[admin_menu][subdir] = "contrib"
projects[advanced_forum][subdir] = "contrib"
projects[author_pane][subdir] = "contrib"
projects[auto_nodetitle][subdir] = "contrib"
projects[autoload][subdir] = "contrib"
projects[backup_migrate][subdir] = "contrib"
projects[service_links][subdir] = "contrib"
projects[better_formats][subdir] = "contrib"
projects[block_class][subdir] = "contrib"
projects[ctools][subdir] = "contrib"
projects[calendar][subdir] = "contrib"
projects[cck_private_fields][subdir] = "contrib"
projects[coder][subdir] = "contrib"
projects[coder_tough_love][subdir] = "contrib"
projects[colorbox][subdir] = "contrib"
projects[contact][subdir] = "contrib"
projects[cck][subdir] = "contrib"
projects[content_access][subdir] = "contrib"
projects[content_profile][subdir] = "contrib"
projects[content_taxonomy][subdir] = "contrib"
projects[cnr][subdir] = "contrib"
projects[custom_breadcrumbs][subdir] = "contrib"
projects[customerror][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[devel][subdir] = "contrib"
projects[email][subdir] = "contrib"
projects[emfield][subdir] = "contrib"
projects[features][subdir] = "contrib"
projects[feeds][subdir] = "contrib"
projects[filefield][subdir] = "contrib"
projects[fivestar][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"
projects[hierarchical_select][subdir] = "contrib"
projects[image_resize_filter][subdir] = "contrib"
projects[imageapi][subdir] = "contrib"
projects[imagecache][subdir] = "contrib"
projects[imagefield][subdir] = "contrib"
projects[imce][subdir] = "contrib"
projects[imce_wysiwyg][subdir] = "contrib"
projects[insert][subdir] = "contrib"
projects[itweak_upload][subdir] = "contrib"
projects[job_scheduler][subdir] = "contrib"
projects[jquery_ui][subdir] = "contrib"
projects[jquery_update][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[location][subdir] = "contrib"
projects[logintoboggan][subdir] = "contrib"
projects[mail_logger][subdir] = "contrib"
projects[maxlength][subdir] = "contrib"
projects[media_vimeo][subdir] = "contrib"
projects[media_youtube][subdir] = "contrib"
projects[menu_block][subdir] = "contrib"
projects[mimemail][subdir] = "contrib"
projects[multicolumncheckboxesradios][subdir] = "contrib"
projects[node_limitnumber][subdir] = "contrib"
projects[nodeaccess_userreference][subdir] = "contrib"
projects[nodeauthor][subdir] = "contrib"
projects[nodehierarchy][subdir] = "contrib"
projects[nodequeue][subdir] = "contrib"
projects[og][subdir] = "contrib"
projects[panels][subdir] = "contrib"
projects[path_redirect][subdir] = "contrib"
projects[pathauto][subdir] = "contrib"
projects[pathologic][subdir] = "contrib"
projects[publishcontent][subdir] = "contrib"
projects[quicktabs][subdir] = "contrib"
projects[revision_deletion][subdir] = "contrib"
projects[rules][subdir] = "contrib"
projects[site_map][subdir] = "contrib"
projects[stringoverrides][subdir] = "contrib"
projects[strongarm][subdir] = "contrib"
projects[tagadelic][subdir] = "contrib"
projects[tagadelic_views][subdir] = "contrib"
projects[terms_of_use][subdir] = "contrib"
projects[token][subdir] = "contrib"
projects[unique_field][subdir] = "contrib"
projects[views][subdir] = "contrib"
projects[views_bonus][subdir] = "contrib"
projects[views_customfield][subdir] = "contrib"
projects[views_datasource][subdir] = "contrib"
projects[views_slideshow][subdir] = "contrib"
projects[votingapi][subdir] = "contrib"
projects[web_widgets][subdir] = "contrib"
projects[webform][subdir] = "contrib"
projects[wysiwyg][subdir] = "contrib"
projects[xmlsitemap][subdir] = "contrib"



; Custom modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[TTtriggers][download][type] = ""
projects[TTtriggers][download][url] = ""
projects[TTtriggers][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ijk_plugins][download][type] = ""
projects[ijk_plugins][download][url] = ""
projects[ijk_plugins][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_extras][download][type] = ""
projects[transition_extras][download][url] = ""
projects[transition_extras][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_project_massage][download][type] = ""
projects[transition_project_massage][download][url] = ""
projects[transition_project_massage][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_pse][download][type] = ""
projects[transition_pse][download][url] = ""
projects[transition_pse][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_sharing_engine_client][download][type] = ""
projects[transition_sharing_engine_client][download][url] = ""
projects[transition_sharing_engine_client][type] = "module"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_site_network][download][type] = ""
projects[transition_site_network][download][url] = ""
projects[transition_site_network][type] = "module"


; Features
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_alert_web_contacts][download][type] = ""
projects[transition_alert_web_contacts][download][url] = ""
projects[transition_alert_web_contacts][type] = "module"
projects[transition_alert_web_contacts][subdir] = "sites/all/modules/custom/features/transition_alert_web_contacts"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_pse_widget][download][type] = ""
projects[transition_pse_widget][download][url] = ""
projects[transition_pse_widget][type] = "module"
projects[transition_pse_widget][subdir] = "sites/all/modules/custom/features/transition_pse_widget"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[initiatives_directory][download][type] = ""
projects[initiatives_directory][download][url] = ""
projects[initiatives_directory][type] = "module"
projects[initiatives_directory][subdir] = "sites/all/modules/custom/features/initiatives_directory"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_events][download][type] = ""
projects[transition_events][download][url] = ""
projects[transition_events][type] = "module"
projects[transition_events][subdir] = "sites/all/modules/custom/features/transition_events"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_import_blogs][download][type] = ""
projects[transition_import_blogs][download][url] = ""
projects[transition_import_blogs][type] = "module"
projects[transition_import_blogs][subdir] = "sites/all/modules/custom/features/transition_import_blogs"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_network_projects][download][type] = ""
projects[transition_network_projects][download][url] = ""
projects[transition_network_projects][type] = "module"
projects[transition_network_projects][subdir] = "sites/all/modules/custom/features/transition_network_projects"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_news][download][type] = ""
projects[transition_news][download][url] = ""
projects[transition_news][type] = "module"
projects[transition_news][subdir] = "sites/all/modules/custom/features/transition_news"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_people][download][type] = ""
projects[transition_people][download][url] = ""
projects[transition_people][type] = "module"
projects[transition_people][subdir] = "sites/all/modules/custom/features/transition_people"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_raise_alerts_for_profiles][download][type] = ""
projects[transition_raise_alerts_for_profiles][download][url] = ""
projects[transition_raise_alerts_for_profiles][type] = "module"
projects[transition_raise_alerts_for_profiles][subdir] = "sites/all/modules/custom/features/transition_raise_alerts_for_profiles"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition_themes][download][type] = ""
projects[transition_themes][download][url] = ""
projects[transition_themes][type] = "module"
projects[transition_themes][subdir] = "sites/all/modules/custom/features/transition_themes"



; Themes
projects[] = "rootcandy"
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition][download][type] = ""
projects[transition][download][url] = ""
projects[transition][type] = "theme"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transition2][download][type] = ""
projects[transition2][download][url] = ""
projects[transition2][type] = "theme"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[transitioncms][download][type] = ""
projects[transitioncms][download][url] = ""
projects[transitioncms][type] = "theme"
